name: Build (Daily)

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  current_info:
    runs-on: ubuntu-latest

    name: Current Information

    outputs:
      tag: ${{ steps.release_info.outputs.tag }}
      version: ${{ steps.release_info.outputs.version }}
      date: ${{ steps.commit_date_iso8601.outputs.date }}
      sha: ${{ github.sha }}
      sha_short: ${{ steps.commit_info.outputs.sha }}

    steps:
      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@master
        with:
          ref: "${{ github.sha }}"
          submodules: recursive
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Get Commit Date (as ISO8601)
        id: commit_date_iso8601
        shell: bash
        env:
          TZ: UTC0
        run: |
          echo "date=$(git --no-pager show -s --date='format-local:%Y-%m-%dT%H:%M:%SZ' --format=%cd ${{ github.sha }})" >> "$GITHUB_OUTPUT"

      - name: Get Previous Version
        id: previous_release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          branch: false
          prefix: "v"
          prefixRegex: "[vV]?"
          suffixRegex: "dev"
          suffix: "dev"

      - name: Get Current Version
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          branch: false
          increment: "suffix"
          prefix: "v"
          prefixRegex: "[vV]?"
          suffixRegex: "dev"
          suffix: "dev"

      - id: commit_info
        name: Shorten Commit Hash
        uses: actions/github-script@v6
        with:
          script: |
            const sha = context.sha.substring(0, 7);
            core.setOutput("sha", sha);

  docker-daily-build:
    runs-on: ubuntu-latest

    needs:
      - current_info

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'amd64'
            dockerfile: 'Dockerfile'

    name: Build Docker Image - ${{ matrix.arch }} (Daily)

    steps:
      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@master
        with:
          ref: "${{ github.sha }}"
          submodules: recursive

      - name: Replace Sentry DSN and other keys
        shell: pwsh
        run: |
          ./.github/workflows/ReplaceSentryDSN.ps1 -dsn ${{ secrets.SENTRY_DSN }}
          ./.github/workflows/ReplaceTmdbApiKey.ps1 -apiKey ${{ secrets.TMDB_API }}
          ./.github/workflows/ReplaceAVD3URL.ps1 -url ${{ secrets.AVD3_URL }}


      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - uses: docker/login-action@v2
        name: Log into GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Disabled provenance for now, until it works with docker manifest create.
      # The manifest list produced by the new feature is incompatible with the
      # expected format used in the docker manifest create command.
      - uses: docker/build-push-action@v4
        name: Build and Push the Docker image
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_REPO }}:latest
          platforms: linux/amd64
          build-args: |
            version=${{ needs.current_info.outputs.version }}
            channel=dev
            commit=${{ needs.current_info.outputs.sha }}
            date=${{ needs.current_info.outputs.date }}
            tag=${{ needs.current_info.outputs.tag }}
          provenance: false
