name: Create Pre-Release (Daily)

on:
  push:
    branches:
      - master

jobs:
  create_prerelease:
    runs-on: ubuntu-latest

    name: Create Pre-Release

    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          ref: "${{ github.ref }}"
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Get next version
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          branch: true
          prefix: v
          prefixRegex: "[vV]?"
          suffix: dev
          increment: suffix

      - name: Create Changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %B" > changelog.txt
          echo 'CHANGELOG<<CHANGELOG_END' >> $GITHUB_ENV
          cat changelog.txt >> $GITHUB_ENV
          echo -e '\nCHANGELOG_END' >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_info.outputs.tag }}
          prerelease: true
          body_path: ./changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cli-framework-daily:
    needs: create_prerelease

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [ '6.x' ]

    name: Build CLI — Framework dependent (Daily)

    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          ref: "${{ github.ref }}"
          submodules: recursive
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Get current version
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          tag: "${{ github.ref }}"
          prefix: v
          prefixRegex: "[vV]?"
          suffix: dev
          increment: suffix

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - run: dotnet publish -c Release --no-self-contained Shoko.CLI "/p:Version=\"${{ steps.release_info.outputs.version }}\",InformationalVersion=\"channel=dev; commit=${{ github.sha }}; tag=${{ steps.release_info.outputs.tag }}\""

      - name: Archive Release
        shell: pwsh
        run: Compress-Archive .\\Shoko.Server\\bin\\Release\\net6.0\\publish .\\Shoko.CLI_Framework_any-x64.zip

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Shoko.CLI*.zip
          tag: ${{ steps.release_info.outputs.tag }}
          file_glob: true

  cli-standalone-daily:
    needs: create_prerelease

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rid: ['win-x64', 'linux-x64']
        dotnet: [ '6.x' ]

    name: Build CLI — Standalone ${{ matrix.rid }} (Daily)

    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          ref: "${{ github.ref }}"
          submodules: recursive
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Get current version
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          tag: "${{ github.ref }}"
          prefix: v
          prefixRegex: "[vV]?"
          suffix: dev
          increment: suffix

      - run: dotnet publish -c Release -r ${{ matrix.rid }} Shoko.CLI "/p:Version=\"${{ steps.release_info.outputs.version }}\",InformationalVersion=\"channel=dev; commit=${{ github.sha }}; tag=${{ steps.release_info.outputs.tag }}\""

      - name: Archive Release (${{ matrix.rid }})
        shell: pwsh
        run: Compress-Archive .\\Shoko.Server\\bin\\Release\\net6.0\\${{ matrix.rid }}\\publish .\\Shoko.CLI_Standalone_${{ matrix.rid }}.zip

      - name: Upload Release (${{ matrix.rid }})
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Shoko.CLI*.zip
          tag: ${{ steps.release_info.outputs.tag }}
          file_glob: true

  tray-service-framework-daily:
    needs: create_prerelease

    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ '6.x' ]

    name: Build Tray Service — Framework dependent (Daily)

    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          ref: "${{ github.ref }}"
          submodules: recursive
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Get current version
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          tag: "${{ github.ref }}"
          prefix: v
          prefixRegex: "[vV]?"
          suffix: dev
          increment: suffix

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - run: dotnet publish -c Release --no-self-contained Shoko.TrayService "/p:Version=\"${{ steps.release_info.outputs.version }}\",InformationalVersion=\"channel=dev; commit=${{ github.sha }}; tag=${{ steps.release_info.outputs.tag }}\""

      - name: Archive Release
        shell: pwsh
        run: Compress-Archive .\\Shoko.Server\\bin\\Release\\net6.0-windows\\win10-x64\\publish .\\Shoko.TrayService_Framework_win10-x64.zip

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Shoko.TrayService*.zip
          tag: ${{ steps.release_info.outputs.tag  }}
          file_glob: true

  tray-service-standalone-daily:
    needs: create_prerelease

    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ '6.x' ]

    name: Build Tray Service — Standalone (Daily)

    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          ref: "${{ github.ref }}"
          submodules: recursive
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Get current version
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          tag: "${{ github.ref }}"
          prefix: v
          prefixRegex: "[vV]?"
          suffix: dev
          increment: suffix

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - run: dotnet publish -c Release -r win10-x64 --self-contained true -f net6.0-windows Shoko.TrayService "/p:Version=\"${{ steps.release_info.outputs.version }}\",InformationalVersion=\"channel=dev; commit=${{ github.sha }}; tag=${{ steps.release_info.outputs.tag }}\""

      - name: Archive Release (for github)
        shell: pwsh
        run: Compress-Archive .\\Shoko.Server\\bin\\Release\\net6.0-windows\\win10-x64\\publish .\\Shoko.TrayService_Standalone_win10-x64.zip

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Shoko.TrayService*.zip
          tag: ${{ steps.release_info.outputs.tag }}
          file_glob: true

      - name: Archive Release (for shokoanime.com)
        shell: pwsh
        run: Compress-Archive .\\Shoko.Server\\bin\\Release\\net6.0-windows\\win10-x64\\publish .\\ShokoServer.zip

      - name: Upload to shokoanime.com
        shell: pwsh
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
        run : .\\.github\\workflows\\UploadArchive.ps1
